version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.javacord:javacord-api
    versions:
    - 3.1.2
    - 3.2.0
  - dependency-name: org.javacord:javacord-core
    versions:
    - 3.1.2
    - 3.2.0
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_227
    - 4.2.0_228
    - 4.2.0_229
    - 4.2.0_230
    - 4.2.0_231
    - 4.2.0_236
    - 4.2.0_239
    - 4.2.0_240
    - 4.2.0_241
    - 4.2.0_242
    - 4.2.0_245
  - dependency-name: org.apache.maven.wagon:wagon-ftp
    versions:
    - 3.4.2
